title: Vivek V Datla
logo: /assets/img/IMG_1712.png
description: A seasoned Computer Scientist with 15 years of expertise in Natural Language Processing, specializing in Large Language Models (LLMs) and Retrieval-Augmented Generation (RAG) systems. Adept at leveraging cutting-edge AI technologies to drive innovation, streamline processes, and deliver impactful, data-driven insights.
show_downloads: false
theme: jekyll-theme-minimal
