title: Vivek V Datla
logo: /assets/img/IMG_1712.png
#description: A seasoned Computer Scientist with 15 years of expertise in Natural Language Processing, specializing in Large Language Models (LLMs) and Retrieval-Augmented Generation (RAG) systems.
show_downloads: false



# Base URL (if your repo is vivekvdatla.github.io, leave blank)
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vivekdatla
  - name: Industry Research
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./industry
  - name: Home
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./about
  - name: Academic Research
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./academics
  - name: Publications
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./publications
  - name: Patents
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./patents
  - name: Awards & Recognitions
    icon: <i class="fa-solid fa-award"></i>
    link: ./awards
  - name: Contact
    icon: <i class="fa-solid fa-ghost"></i>
    link: ./contact

theme: jekyll-theme-minimal