title: Vivek V Datla
logo: /assets/img/IMG_1712.png
description: A seasoned Computer Scientist with 15 years of expertise in Natural Language Processing, specializing in Large Language Models (LLMs) and Retrieval-Augmented Generation (RAG) systems.
show_downloads: false
theme: jekyll-theme-minimal
